### ISSUE TITLE
CrashLooping

### ISSUE THREAD

**Issue by outbackdingo** [cdwv/bitwarden-k8s#4]
seems the chart is no longer valid as stated https://hub.docker.com/r/mprasil/bitwarden

This used to be the official bitwarden_rs image. The project has now been moved to https://hub.docker.com/r/bitwardenrs/server

**Comment by rgembalik** [comment]
You're right. We'll have to do some testing before we can push an update, to make sure it's not a breaking change for our chart, especially for the vault database itself.

**Comment by outbackdingo** [comment]
ive modified the  image in the yaml locally and deployed it, it does appears to be working for me

**Comment by outbackdingo** [comment]
diff --git a/values.yaml b/values.yaml
index d890b92..32638ab 100644
--- a/values.yaml
+++ b/values.yaml
@@ -2,10 +2,8 @@
 # This is a YAML-formatted file.
 # Declare variables to be passed into your templates.
 
-replicaCount: 1
-
 image:
-  repository: mprasil/bitwarden
+  repository: bitwardenrs/server
   tag: latest
   pullPolicy: IfNotPresent

**Comment by rgembalik** [comment]
@outbackdingo Hey, sorry it took me so much time, but I included that change in the latest version of the chart.
